USE [master]
GO

/****** Object:  Database [datanthing]    Script Date: 13/6/2020 1:29:22 πμ ******/
CREATE DATABASE [datanthing]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'datanthing', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SRSQLSERVER17\MSSQL\DATA\datanthing.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'datanthing_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SRSQLSERVER17\MSSQL\DATA\datanthing_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [datanthing] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [datanthing].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [datanthing] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [datanthing] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [datanthing] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [datanthing] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [datanthing] SET ARITHABORT OFF 
GO

ALTER DATABASE [datanthing] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [datanthing] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [datanthing] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [datanthing] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [datanthing] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [datanthing] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [datanthing] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [datanthing] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [datanthing] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [datanthing] SET  DISABLE_BROKER 
GO

ALTER DATABASE [datanthing] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [datanthing] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [datanthing] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [datanthing] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [datanthing] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [datanthing] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [datanthing] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [datanthing] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [datanthing] SET  MULTI_USER 
GO

ALTER DATABASE [datanthing] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [datanthing] SET DB_CHAINING OFF 
GO

ALTER DATABASE [datanthing] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [datanthing] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [datanthing] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [datanthing] SET QUERY_STORE = OFF
GO

ALTER DATABASE [datanthing] SET  READ_WRITE 
GO

